app.py
from flask import Flask, redirect, request, url_for, render_template,session
import spotipy
from spotipy.oauth2 import SpotifyOAuth
from blueprints.auth import auth_bp
from blueprints.home import home_bp





# client id: 794f04ed0af847559a4f79264ab0c369

# client secret; 5b24cedab54749979222a8906aca3b24



#le tue credenziali le trovi nella dashboard di prima

app = Flask(__name__)
app.secret_key = 'chiave_per_session' #ci serve per identificare la sessione



app.register_blueprint(auth_bp)
app.register_blueprint(home_bp)



#configurazione SpotifyOAuth per l'autenticazione e redirect uri



if __name__ == '__main__': #debug
    app.run(debug=True)

blueprints/auth.py
from flask import Blueprint, redirect, request, url_for, session
from services.spotify_oauth import sp_oauth

auth_bp = Blueprint('auth', __name__)

@auth_bp.route('/')
def login():
    auth_url = sp_oauth.get_authorize_url()
    return redirect(auth_url)

@auth_bp.route('/callback')
def callback():
    code = request.args.get('code')
    token_info = sp_oauth.get_access_token(code)
    session['token_info'] = token_info
    return redirect(url_for('home.homepage'))

@auth_bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('auth.login'))

blueprints/home.py
from flask import Blueprint, session, redirect, url_for, render_template
import spotipy

home_bp = Blueprint('home', __name__)

@home_bp.route('/home')
def homepage():
    token_info = session.get('token_info')
    if not token_info:
        return redirect(url_for('auth.login'))

    sp = spotipy.Spotify(auth=token_info['access_token'])
    user_info = sp.current_user()
    playlists = sp.current_user_playlists()['items']

    return render_template('home.html', user_info=user_info, playlists=playlists)





@home_bp.route('/playlist/<playlist_id>')
def playlist_tracks(playlist_id):
    token_info = session.get('token_info')
    if not token_info:
        return redirect(url_for('auth.login'))

    sp = spotipy.Spotify(auth=token_info['access_token'])
    playlist = sp.playlist_items(playlist_id, limit=100)

    tracks = [{'name': item['track']['name'],
               'artist': ', '.join([artist['name'] for artist in item['track']['artists']]),
               'album': item['track']['album']['name']} for item in playlist['items']]

    return render_template('playlist.html', tracks=tracks)

templates/home.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    
        <title> Profilo Utente</title>
    
    
    </head>


    <body>
        
        <div style="text-align: right;">
            <a href="{{ url_for('auth.logout') }}" style="color: blue; text-decoration: none; font-weight: bold;">Logout</a>
        </div>
        
        
        
        <h1>Benvenuto, {{ user_info['display_name'] }}!</h1>
        
        {% if user_info['images'] %}
            <img src="{{ user_info['images'][1]['url'] }}" width="200">
        
        {% endif %}
    
        
        <h2>Playlist salvate</h2>
    
        {% if playlists %}

            <table>

                <Shead>

                    <tr>

                        <th>/Nome Playlist\</th>

                        <th>/Numero di brani\</th>

                        <th>/Copertina\</th>






                    </tr>













                </Shead>

                <Sbody>
                    
                    {% for playlist in playlists %}

                        <tr>

                            <td>{{ playlist['name'] }}</td>

                            <td>{{ playlist['tracks']['total']}}</td>

                            <td>

                                {% if playlist['images'] %}

                                    <img src="{{ playlist['images'][0]['url'] }}" width="50" alt="Copertina playlist">

                                {% else %}

                                    immagine non presente


                                {% endif %}

                                <br>

                                <a href="{{ url_for('home.playlist_tracks', playlist_id=playlist['id']) }}">Visualizza Brani</a>



                            </td>






                        </tr>

                
                
                    {% endfor %}    
                
                
                
                
                </Sbody>







            </table>
    
    
    
        {% else %}
    
            <p>nessuna playlist disponibile</p>
    
        {% endif %}
    
    
    
    
    
    
    </body>

</html>

templates/playlist.html
<!DOCTYPE html>
<html lang="it">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Brani della Playlist</title> 
</head>
<body>
    <h1>Brani:</h1>
    <table border="1">
        <tr>
            <th>Titolo</th>
            <th>Artista</th>
            <th>Album</th>
        </tr>
        {% for track in tracks %} 
        <tr>
            <td>{{ track['name'] }}</td>
            <td>{{ track['artist'] }}</td>
            <td>{{ track['album'] }}</td>
        </tr>
        {% endfor %}
    </table>
    <br>
    <a href="{{ url_for('home.homepage') }}">Torna alla Home</a>
</body>
</html>